[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_FIREBASE_API_KEY = "build-placeholder"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "build-placeholder"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "build-placeholder"
  NEXT_PUBLIC_FIREBASE_APP_ID = "build-placeholder"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/api/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600, s-maxage=3600"